# Dependencies needed for working on the this code and repo.
# This does *not* include the dependencies of poprox-recommender itself —
# it is only the tooling and dependencies for development, image building,
# etc.  It is included in the conda lockfile as the 'dev' category, and
# can be directly installed in CI for repo manipulation.
category: dev
dependencies:
  - hatch
  # dependencies for tests
  - coverage >=6.5
  - pytest >=8
  # tooling for code validation
  - pre-commit >=3.7,<4
  - ruff >=0.4
  - pyright >=1.1,<2
